import { DM_Sans, Poppins } from 'next/font/google'
import "/public/app/dist/app.css"
import "/public/app/dist/swiper-bundle.min.css"
import ProtectedRoute from '../components/ProtectedRoute'
import { AuthProvider } from "@/components/context/AuthContext"

const poppins = Poppins({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
  variable: "--poppins",
  display: 'swap',
})

const dm = DM_Sans({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
  variable: "--dm",
  display: 'swap',
})

export const metadata = {
  title: 'Xpero',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.variable} ${dm.variable}`}>
    <head>
      <link
        href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded"
        rel="stylesheet"
      />
    </head>
    <body>
      <AuthProvider>
        <ProtectedRoute>
          {children}
        </ProtectedRoute>
      </AuthProvider>
    </body>
  </html>  

  )
}
